spring.application.name=tracker
server.port=8080

spring.datasource.url=jdbc:mysql://192.168.1.50:3306/expense_tracker
spring.datasource.username=piyush
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

SECRET_KEY=9f4c2d7a8b13e6f1c0a54d9b72ef34c18d6a0b9e5f3271ac4d8e6b2f91c3a7de

